version: '1.0'

stages:
- Build
- Push

steps:

  CloneServices:
    title: Clone Services Repo
    type: git-clone
    repo: open-integration/service-catalog
    git: cf_github
    revision: ${{CF_REVISION}}

  BuildServices:
    stage: Build
    title: Build Services
    image: golang:1.13.5-alpine3.10
    working_directory: ${{CloneServices}}
    commands:
    - rm -rf dist || true 
    - apk update && apk add git make py-pip jq
    - pip install yq
    - go get -u github.com/gobuffalo/packr/packr
    - git remote rm origin
    - git remote add origin https://olegsu:${{GITHUB_TOKEN}}@github.com/open-integration/service-catalog.git
    - sh ./.scripts/build.sh
    - echo $GOOGLE_SERVICE_ACCOUNT_B64 | base64 -d - > ${{CF_VOLUME_PATH}}/service-account.json
    - cf_export KEY_FILE_PATH=${{CF_VOLUME_PATH}}/service-account.json 
    
    
    - cf_export SERVICE_GIT_VERSION=$(cat git/VERSION)
    - cf_export SERVICE_GOOGLE_SPREADSHEET_VERSION=$(cat google-spreadsheet/VERSION)
    - cf_export SERVICE_TRELLO_VERSION=$(cat trello/VERSION)
    - cf_export SERVICE_JIRA_VERSION=$(cat jira/VERSION)
    - cf_export SERVICE_SLACK_VERSION=$(cat slack/VERSION)
    - cf_export SERVICE_KUBERNETES_VERSION=$(cat kubernetes/VERSION)
    - cf_export SERVICE_EXEC_VERSION=$(cat exec/VERSION)

  BuildImages:
    stage: Build
    title: Build All Docker Images
    type: parallel
    steps:
      git: &dockerbuild
        title: "Build Docker Image"
        type: build
        working_directory: ${{CloneServices}}
        image_name: service_catalog/git
        dockerfile: git/Dockerfile
        registry: dockerhub
        build_arguments:
          - NAME=git-${{SERVICE_GIT_VERSION}}-linux-amd64
          - DIR=git
      slack:
        <<: *dockerbuild
        dockerfile: docker/Dockerfile
        image_name: service_catalog/slack
        build_arguments:
          - NAME=slack-${{SERVICE_SLACK_VERSION}}-linux-amd64
          - DIR=slack
      exec:
        <<: *dockerbuild
        dockerfile: docker/Dockerfile
        image_name: service_catalog/exec
        build_arguments:
          - NAME=slack-${{SERVICE_EXEC_VERSION}}-linux-amd64
          - DIR=exec
      jira:
        <<: *dockerbuild
        dockerfile: docker/Dockerfile
        image_name: service_catalog/jira
        build_arguments:
          - NAME=jira-${{SERVICE_JIRA_VERSION}}-linux-amd64
          - DIR=jira
      google-spreadsheet:
        <<: *dockerbuild
        dockerfile: google-spreadsheet/Dockerfile
        image_name: service_catalog/google-spreadsheet
        build_arguments:
          - NAME=google-spreadsheet-${{SERVICE_GOOGLE_SPREADSHEET_VERSION}}-linux-amd64
          - DIR=google-spreadsheet
      trello:
        <<: *dockerbuild
        dockerfile: trello/Dockerfile
        image_name: service_catalog/trello
        build_arguments:
          - NAME=trello-${{SERVICE_TRELLO_VERSION}}-linux-amd64
          - DIR=trello
      kubernetes:
        <<: *dockerbuild
        dockerfile: kubernetes/Dockerfile
        image_name: service_catalog/kubernetes
        build_arguments:
          - NAME=kubernetes-${{SERVICE_KUBERNETES_VERSION}}-linux-amd64
          - DIR=kubernetes
    when:
      branch:
        only:
        - master

  PushImages:
    stage: Push
    title: Push All Docker Images To Dockerhub
    type: parallel
    steps:
      push-git: &pushImage
        title: "Push Docker Image"
        type: push
        candidate: ${{git}}
        image_name: openintegration/service_catalog-git
        registry: dockerhub
        tags:
        - latest
        - ${{SERVICE_GIT_VERSION}}
      push-jira:
        <<: *pushImage
        candidate: ${{jira}}
        image_name: openintegration/service_catalog-jira
        tags:
        - latest
        - ${{SERVICE_JIRA_VERSION}}
      push-slack:
        <<: *pushImage
        candidate: ${{slack}}
        image_name: openintegration/service_catalog-slack
        tags:
        - latest
        - ${{SERVICE_SLACK_VERSION}}
      push-exec:
        <<: *pushImage
        candidate: ${{exec}}
        image_name: openintegration/service_catalog-exec
        tags:
        - latest
        - ${{SERVICE_EXEC_VERSION}}
      push-google-spreadsheet:
        <<: *pushImage
        candidate: ${{google-spreadsheet}}
        image_name: openintegration/service_catalog-google-spreadsheet
        tags:
        - latest
        - ${{SERVICE_GOOGLE_SPREADSHEET_VERSION}}
      push-trello:
        <<: *pushImage
        candidate: ${{trello}}
        image_name: openintegration/service_catalog-trello
        tags:
        - latest
        - ${{SERVICE_TRELLO_VERSION}}
      push-kubernetes:
        <<: *pushImage
        candidate: ${{kubernetes}}
        image_name: openintegration/service_catalog-kubernetes
        tags:
        - latest
        - ${{SERVICE_KUBERNETES_VERSION}}
    when:
      branch:
        only:
        - master

  CreateRelease:
    stage: Push
    title: Create Release
    image: google/cloud-sdk
    working_directory: ${{CloneServices}}
    commands:
    - echo "Running script"
    - sh ./.scripts/publish.sh
    when:
      branch:
        only:
        - master